# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainFile.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(584, 523)
        MainWindow.setMinimumSize(QtCore.QSize(584, 523))
        MainWindow.setMaximumSize(QtCore.QSize(584, 523))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(70, 400, 451, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.DisplayProject = QtWidgets.QFrame(self.centralwidget)
        self.DisplayProject.setGeometry(QtCore.QRect(90, 130, 391, 251))
        self.DisplayProject.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DisplayProject.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DisplayProject.setObjectName("DisplayProject")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 220, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 341, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 28pt \"MS Shell Dlg 2\"; \n"
"color: rgb(255, 255, 255);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 250, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 80, 301, 20))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.port = QtWidgets.QLabel(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(110, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(True)
        font.setWeight(75)
        self.port.setFont(font)
        self.port.setStyleSheet("color: rgb(216, 0, 0);")
        self.port.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.port.setObjectName("port")
        self.copyright = QtWidgets.QLabel(self.centralwidget)
        self.copyright.setGeometry(QtCore.QRect(20, 460, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        self.copyright.setFont(font)
        self.copyright.setAutoFillBackground(False)
        self.copyright.setStyleSheet("color: rgb(239, 0, 0);")
        self.copyright.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.copyright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.copyright.setObjectName("copyright")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(0, 0, 701, 481))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("rsz_redstarincllc.png"))
        self.Image.setObjectName("Image")
        self.Image.raise_()
        self.progressBar.raise_()
        self.DisplayProject.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_2.raise_()
        self.port.raise_()
        self.copyright.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 21))
        self.menubar.setObjectName("menubar")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        self.menuContact_Us = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setItalic(True)
        self.menuContact_Us.setFont(font)
        self.menuContact_Us.setObjectName("menuContact_Us")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuQuit.menuAction())
        self.menubar.addAction(self.menuContact_Us.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Port Scanner"))
        self.pushButton_3.setText(_translate("MainWindow", "Reset"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Please enter the Port Number"))
        self.port.setText(_translate("MainWindow", "Port:"))
        self.copyright.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; text-decoration: underline;\">Copyright @ Texas Southern University CISSA</span></p></body></html>"))
        self.menuQuit.setTitle(_translate("MainWindow", "Quit"))
        self.menuContact_Us.setTitle(_translate("MainWindow", "Contact Us"))

